service: pets
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  stage: dev
  profile: pet-dev
  environment: ${file(serverless.variables.${opt:stage,self:provider.stage}.yml)}

functions:
  pet-create:
    handler: src/functions/pet/pet-controller.create
    events:
      - httpApi:
          path: /pet-create
          method: post
  pet-update:
    handler: src/functions/pet/pet-controller.update
    events:
      - httpApi:
          path: /pet-update/{id}
          method: PATCH
  pet-all:
    handler: src/functions/pet/pet-controller.getAll
    events:
      - httpApi:
          method: get
          path: /pet
  pet-all-with-childs:
    handler: src/functions/pet/pet-controller.getAllWithChilds
    events:
      - httpApi:
          method: get
          path: /pet-with-childs
  pet-get-by-id:
    handler: src/functions/pet/pet-controller.getById
    events:
      - httpApi:
          method: get
          path: /pet/{id}
  pet-delete:
    handler: src/functions/pet/pet-controller.detele
    events:
      - httpApi:
          method: delete
          path: /pet/{id}
  pet-add-child:
    handler: src/functions/pet/pet-controller.addChilds
    events:
      - httpApi:
          path: /pet/{id}/add-childs
          method: post
  pet-remove-child:
    handler: src/functions/pet/pet-controller.removeChild
    events:
      - httpApi:
          path: /pet/{id}/{childId}
          method: delete
  user:
    handler: src/functions/user.handler
    events:
      - httpApi:
          path: /user
          method: get

plugins:
  - serverless-plugin-typescript
  - serverless-offline
