service: pets
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  stage: dev
  profile: pet-dev
  environment:
    MONGO_URL: mongodb://localhost:27018/petsdb
    STAGE: ${self:provider.stage}

functions:
  pet-create:
    handler: src/functions/pet/pet-controller.create
    events:
      - httpApi:
          path: /pet-create
          method: post
  pet-all:
    handler: src/functions/pet/pet-controller.getAll
    events:
      - httpApi:
          method: get
          path: /pet
  pet-get-by-id:
    handler: src/functions/pet/pet-controller.getById
    events:
      - httpApi:
          method: get
          path: /pet/{id}

  user:
    handler: src/functions/user.handler
    events:
      - httpApi:
          path: /user
          method: get

plugins:
  - serverless-plugin-typescript
  - serverless-offline
